language: c

install:
 - pip install --user cmake

before_script:
 - git clone https://github.com/bluezephyr/bitloom-core.git --branch=refactor-i2c ~/bitloom-core
 - git clone https://github.com/cpputest/cpputest.git ~/cpputest
 - cd ~/cpputest
 - ./autogen.sh
 - cd cpputest_build
 - ../configure
 - make -j
 - cd ${TRAVIS_BUILD_DIR}
 - mkdir build
 - cd build

script:
 - cmake -DBITLOOM_CORE=~/bitloom-core -DCPPUTEST_HOME=~/cpputest ..
 - make all -j
 - make test
